name: Publish Next Version

on:
  push:
    branches:
      - master
    paths:
      - "lib/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/

      - name: Install lib dependencies
        run: cd lib && npm i

      - name: Build library
        run: cd lib && npm run build

      - name: Test library
        run: cd lib && npm run test

      - name: Publish NEXT version to npm
        run: |
          sed -i "s#\"version\": \"0.0.0\"#\"version\": \"0.0.0-${GITHUB_SHA:0:7}\"#" ./lib/dist/package.json
          cd lib
          cd dist
          npm publish --tag next --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
